services:
  redis:
    image: redis:7-alpine
    container_name: renova-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - renova-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: renova-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - renova-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: renova-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - chroma_data:/app/chroma_data
    depends_on:
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - renova-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend/Landing Page AI
      dockerfile: Dockerfile
    container_name: renova-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend/Landing Page AI:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - renova-network
    command: npm run dev

volumes:
  redis_data:
    driver: local
  chroma_data:
    driver: local

networks:
  renova-network:
    driver: bridge
