version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: renova-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: renova-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./chroma_data:/app/chroma_data
    depends_on:
      redis:
        condition: service_healthy
    command: npm run dev

  frontend:
    build:
      context: ./frontend/Landing Page AI
      dockerfile: Dockerfile
    container_name: renova-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend/Landing Page AI:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  redis_data:
